### ISSUE TITLE
flatten throws an error

### ISSUE THREAD

**Issue by TvL2386** [ninech/netbox-client-ruby#39]
I've worked around this issue by concatting arrays, however, I think it is a bug that the following code throws an error:

```
> [[NetboxClientRuby::DCIM::Interface.new(name: 'ge-0/0/0', device_id: 488)]].flatten
NetboxClientRuby::LocalError: Received 'nil' while replacing ':id' in 'dcim/interfaces/:id.json' with a value.
from /usr/local/bundle/gems/netbox-client-ruby-0.5.2/lib/netbox_client_ruby/entity.rb:310:in `block in replace_path_variables_in'
```

The problem is Interface responds to flatten and throws an error:
```
> NetboxClientRuby::DCIM::Interface.new(name: 'ge-0/0/0', device_id: 488).flatten
NetboxClientRuby::LocalError: Received 'nil' while replacing ':id' in 'dcim/interfaces/:id.json' with a value.
from /usr/local/bundle/gems/netbox-client-ruby-0.5.2/lib/netbox_client_ruby/entity.rb:310:in `block in replace_path_variables_in'
```

**Comment by thde** [comment]
Hey @TvL2386, thanks for the report! I'm happy to review and merge if you find time for a PR.

**Comment by TvL2386** [comment]
Hi @thde, you're welcome. I've tried to fix it, PR incoming.

**Comment by thde** [comment]
Released:
https://github.com/ninech/netbox-client-ruby/releases/tag/0.5.3
